---
name: Lingua-Slavic-Numbers
version: 0.03
author:
  - 'Ted Zlatanov <tzz@lifelogs.com>'
abstract: |-
  Converts numeric values into their Slavic
  string equivalents.  Bulgarian is supported so far.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  List::Util: 0
  Regexp::Common: 0
  perl: 5.6.1
provides:
  Lingua::BG::Numbers:
    file: lib/Lingua/BG/Numbers.pm
    version: 0.02
  Lingua::Slavic::Numbers:
    file: lib/Lingua/Slavic/Numbers.pm
    version: 0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
