--- #YAML:1.0
name:                Lingua-Slavic-Numbers
version:             0.01
abstract:            Converts numeric values into their Slavic
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    List::Util:                    1
    Regexp::Common:                1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ted Zlatanov <tzz@lifelogs.com>
