name: CI

on:
  push:
    branches-ignore:
      - '*travis*'
      - '*appveyor*'
      - '*doozer*'
  pull_request:
  workflow_dispatch:

jobs:
  create-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prereqs
        run: |
          sudo apt-get update -q
          sudo apt-get install -qy --no-install-recommends libmodule-build-perl
      - name: Create dist
        run: |
          perl Build.PL
          ./Build
          ./Build dist
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: "*.tar.gz"

  test:
    name: Test with perl ${{ matrix.perlimage }}
    runs-on: ubuntu-latest
    container: perl:${{ matrix.perlimage }}
    strategy:
      matrix:
        include:
          - perlimage: 5.8.9-threaded-stretch
          - perlimage: 5.10.1-buster
          - perlimage: 5.12.5-stretch
          - perlimage: 5.14.4-stretch
          - perlimage: 5.16.3-buster
          - perlimage: 5.18.4-buster
          - perlimage: 5.22.4-stretch
          - perlimage: 5.30.3-threaded-buster
          - perlimage: 5.36.0-slim-bullseye
          - perlimage: 5.38.0-slim-bookworm
    needs: create-dist
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Prereqs for older perls
        run: |
          perl -e 'exit($] >= 5.010 ? 0 : 1)' || cpanm Regexp::Common@2016020301
      - name: Test with cpanm
        run: |
          cpanm --test --verbose *.tar.gz
